### ISSUE TITLE
 Automatic Database Designer run error

### ISSUE THREAD

**Issue by chpooo** [apavlo/h-store#193]
Firstly, in "build.xml",  in "<target name='designer-prepare'",
the antcall stats should be workload-stats. Am I right?

I found this code could't run. Let's take tm1 for example:
I downloaded tm1-1.trace.gz and put it into files/workloads/
then I run "ant designer-prepare -Dproject=tm1 -Dtarget.workload=tm1-1 -Dscalefactor=1.0"
here is the log.

Buildfile: /data0/xianke/hstore/build.xml

designer-prepare:
     [echo] Creating table stats file for tm1...
     [java] 16:09:50,486 [main] (AbstractTableStatisticsGenerator.java:218) INFO  - Generating TableStatistics for 4 tables with scale factor 1.0
     [java] 16:09:50,506 [main] (AbstractTableStatisticsGenerator.java:249) INFO  - SUBSCRIBER                     100000          [0.01GB]
     [java] 16:09:50,509 [main] (AbstractTableStatisticsGenerator.java:295) INFO  - SPECIAL_FACILITY               250001          [0.00GB]
     [java] 16:09:50,510 [main] (AbstractTableStatisticsGenerator.java:295) INFO  - CALL_FORWARDING                375003          [0.01GB]
     [java] 16:09:50,510 [main] (AbstractTableStatisticsGenerator.java:295) INFO  - ACCESS_INFO                    250001          [0.00GB]
     [java] 16:09:50,517 [main] (AbstractTableStatisticsGenerator.java:309) INFO  - ------------------------------------------------------------
     [java] 16:09:50,517 [main] (AbstractTableStatisticsGenerator.java:310) INFO  - TOTAL SIZE                     975005          [0.02GB]
     [echo] Creating stats file for workload 'tm1-1' using '/data0/xianke/hstore/obj/stats/tm1.stats' as base

workload-stats:
     [java] 16:09:56,223 [main] (Workload.java:425) INFO  - Loaded 379882 txns / 468556 queries from 'tm1-1.trace.gz' in 4.8 seconds using 4 threads
     [java] 16:09:56,241 [main] (WorkloadStatistics.java:331) INFO  - Workload Histogram:
     [java] UpdateSubscriberData [  7504] ****
     [java] InsertCallForwarding [  7652] ****
     [java] GetSubscriberData    [132592] *******************************************************************************
     [java] DeleteCallForwarding [  7649] ****
     [java] GetAccessData        [133103] ********************************************************************************
     [java] GetNewDestination    [ 38144] **********************
     [java] UpdateLocation       [ 53238] *******************************
     [java] 16:09:56,241 [main] (WorkloadStatistics.java:156) INFO  - Invoking preprocess methods on statistics objects for edu.brown.workload.Workload@28b6483
     [java] 16:09:56,241 [main] (WorkloadStatistics.java:171) INFO  - Invoking process methods on statistics objects for edu.brown.workload.Workload@28b6483
     [java] 16:09:56,247 [main] (WorkloadStatistics.java:209) ERROR - Failed to process TransactionTrace[UpdateLocation:#10012]
     [java] java.lang.NullPointerException
     [java] 	at edu.brown.statistics.ProcedureStatistics.process(ProcedureStatistics.java:205)
     [java] 	at edu.brown.statistics.ProcedureStatistics.process(ProcedureStatistics.java:153)
     [java] 	at edu.brown.statistics.WorkloadStatistics.process(WorkloadStatistics.java:198)
     [java] 	at edu.brown.statistics.WorkloadStatistics.main(WorkloadStatistics.java:337)

BUILD FAILED
/data0/xianke/hstore/build.xml:2285: The following error occurred while executing this line:
/data0/xianke/hstore/build.xml:2074: Java returned: 1

**Comment by apavlo** [comment]
I fixed the NulPointerExceptions.

There are a bunch of pre-generated stats files that are available that you could use instead:

https://database.cs.brown.edu/svn/hstore-files/stats/

Let met know if anything else comes up.

**Comment by chpooo** [comment]
Thanks, But another NullPointerExceptions happens when I run
ant designer-benchmark -Dproject=tm1 -Dworkload=files/workloads/tm1-1.trace.gz 
-Dstats=files/stats/tm1.stats.gz -Dhints=files/designhints/tm1.hints -Dlimit=5000 
-Dpartitioner=edu.brown.designer.partitioners.BranchAndBoundPartitioner 
-Dcostmodel=edu.brown.costmodel.SingleSitedCostModel

Log is as follows:

Buildfile: /data0/xianke/h-store/build.xml

designer-benchmark:
     [java] 21:52:39,234 [main] (Workload.java:425) INFO  - Loade4 threads
     [java] TEMP DIR: ${output.dir}/
     [java] Exception in thread "main" java.lang.NullPointerExcep
     [java] 	at edu.brown.designer.generators.AccessGraphGener
     [java] 	at edu.brown.designer.generators.AccessGraphGener
     [java] 	at edu.brown.designer.generators.AccessGraphGener
     [java] 	at edu.brown.designer.Designer.init(Designer.java
     [java] 	at edu.brown.designer.Designer.<init>(Designer.ja
     [java] 	at edu.brown.designer.Designer.main(Designer.java

BUILD FAILED
/data0/xianke/h-store/build.xml:2326: Java returned: 1
