### ISSUE TITLE
Master branch does not compile successfully on Mac OX (10.10.4) at least

### ISSUE THREAD

**Issue by jxchinaren** [apavlo/h-store#201]
Seems to have problems using berkeleydb on MAC OX?

[exec] ar cr libdb_cxx-5.3.a cxx_channel.o cxx_db.o cxx_dbc.o cxx_dbt.o cxx_env.o cxx_except.o cxx_lock.o cxx_logc.o cxx_mpool.o cxx_multi.o cxx_rid.o cxx_seq.o cxx_site.o cxx_txn.o mut_tas.o  bt_compare.o bt_compress.o bt_conv.o bt_curadj.o bt_cursor.o bt_delete.o bt_method.o bt_open.o bt_put.o bt_rec.o bt_reclaim.o bt_recno.o bt_rsearch.o bt_search.o bt_split.o bt_stat.o bt_compact.o bt_upgrade.o btree_auto.o hash.o hash_auto.o hash_compact.o hash_conv.o hash_dup.o hash_meta.o hash_method.o hash_open.o hash_page.o hash_rec.o hash_reclaim.o hash_stat.o hash_upgrade.o hash_verify.o heap_stub.o qam_stub.o rep_stub.o repmgr_stub.o db_ovfl_vrfy.o db_vrfy.o db_vrfyutil.o bt_verify.o log_verify.o log_verify_util.o log_verify_int.o log_verify_auto.o  lock.o lock_deadlock.o lock_failchk.o lock_id.o lock_list.o lock_method.o lock_region.o lock_stat.o lock_timer.o lock_util.o mut_alloc.o mut_failchk.o mut_method.o mut_region.o mut_stat.o  crypto_stub.o clock.o crdel_auto.o crdel_rec.o db.o db_am.o db_auto.o db_backup.o db_byteorder.o db_cam.o db_cds.o db_compact.o db_compint.o db_conv.o db_copy.o db_dispatch.o db_dup.o db_err.o db_getlong.o db_idspace.o db_iface.o db_join.o db_log2.o db_meta.o db_method.o db_open.o db_overflow.o db_pr.o db_rec.o db_reclaim.o db_remove.o db_rename.o db_ret.o db_setid.o db_setlsn.o db_shash.o db_sort_multiple.o db_stati.o db_truncate.o db_upg.o db_upg_opd.o dbreg.o dbreg_stat.o dbreg_auto.o dbreg_rec.o dbreg_util.o dbt.o env_alloc.o env_config.o env_backup.o env_failchk.o env_file.o env_globals.o env_open.o env_method.o env_name.o env_recover.o env_region.o env_register.o env_sig.o env_stat.o fileops_auto.o fop_basic.o fop_rec.o fop_util.o hash_func.o hmac.o log.o log_archive.o log_compare.o log_debug.o log_get.o log_method.o log_print.o log_put.o log_stat.o mkpath.o mp_alloc.o mp_backup.o mp_bh.o mp_fget.o mp_fmethod.o mp_fopen.o mp_fput.o mp_fset.o mp_method.o mp_mvcc.o mp_region.o mp_register.o mp_resize.o mp_stat.o mp_sync.o mp_trickle.o openflags.o os_abort.o os_abs.o os_alloc.o os_clock.o os_cpu.o os_ctime.o os_config.o os_dir.o os_errno.o os_fid.o os_flock.o os_fsync.o os_getenv.o os_handle.o os_map.o os_method.o os_mkdir.o os_open.o os_path.o os_pid.o os_rename.o os_root.o os_rpath.o os_rw.o os_seek.o os_stack.o os_stat.o os_tmpdir.o os_truncate.o os_uid.o os_unlink.o os_yield.o partition.o seq_stat.o sequence.o sha1.o snprintf.o txn.o txn_auto.o txn_chkpt.o txn_failchk.o txn_method.o txn_rec.o txn_recover.o txn_region.o txn_stat.o txn_util.o xa.o xa_map.o zerofill.o  
     [exec] ranlib libdb-5.3.a
     [exec] /Users/xin/git/h-store/third_party/cpp/berkeleydb/util/db_tuner.c:1114:12: warning: promoted type 'int' of K&R function parameter is not compatible with the parameter type 'db_indx_t' (aka 'unsigned short') declared in a previous prototype [-Wknr-promoted-parameter]
     [exec]         db_indx_t indx;
     [exec]                   ^
     [exec] /Users/xin/git/h-store/third_party/cpp/berkeleydb/util/db_tuner.c:127:51: note: previous declaration is here
     [exec] static int item_space __P((DB *, PAGE *, db_indx_t));
     [exec]                                                   ^
     [exec] ./db.h:40:21: note: expanded from macro '__P'
     [exec] #define __P(protos)     protos
     [exec]                         ^
     [exec] /Users/xin/git/h-store/third_party/cpp/berkeleydb/util/db_tuner.c:1126:12: warning: promoted type 'int' of K&R function parameter is not compatible with the parameter type 'db_indx_t' (aka 'unsigned short') declared in a previous prototype [-Wknr-promoted-parameter]
     [exec]         db_indx_t indx;
     [exec]                   ^
     [exec] /Users/xin/git/h-store/third_party/cpp/berkeleydb/util/db_tuner.c:126:50: note: previous declaration is here
     [exec] static int item_size __P((DB *, PAGE *, db_indx_t));
     [exec]                                                  ^
     [exec] ./db.h:40:21: note: expanded from macro '__P'
     [exec] #define __P(protos)     protos
     [exec]                         ^
     [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdb-5.3.a(snprintf.o) has no symbols
     [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdb_cxx-5.3.a(snprintf.o) has no symbols
     [exec] ranlib libdb_cxx-5.3.a
     [exec] rm -f libdb.a
     [exec] ln -s libdb-5.3.a libdb.a
     [exec] ./libtool --mode=link cc -O3  -o db_archive  \
     [exec] 	    db_archive.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_checkpoint  \
     [exec] 	    db_checkpoint.o util_log.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_deadlock  \
     [exec] 	    db_deadlock.o util_log.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_dump  \
     [exec] 	    db_dump.o util_cache.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_hotbackup  \
     [exec] 	    db_hotbackup.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_load  \
     [exec] 	    db_load.o util_cache.o util_sig.o libdb-5.3.a -lpthread
     [exec] rm -f libdb_cxx.a
     [exec] ln -s libdb_cxx-5.3.a libdb_cxx.a
     [exec] ./libtool --mode=link cc -O3  -o db_log_verify  \
     [exec] 	    db_log_verify.o util_cache.o util_sig.o libdb-5.3.a -lpthread
     [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdb-5.3.a(snprintf.o) has no symbols
     [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdb_cxx-5.3.a(snprintf.o) has no symbols
     [exec] libtool: link: cc -O3 -o db_dump db_dump.o util_cache.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_load db_load.o util_cache.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_archive db_archive.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_checkpoint db_checkpoint.o util_log.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_deadlock db_deadlock.o util_log.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_hotbackup db_hotbackup.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_log_verify db_log_verify.o util_cache.o util_sig.o  libdb-5.3.a -lpthread
     [exec] :  db_hotbackup
     [exec] :  db_archive
     [exec] :  db_dump
     [exec] :  db_deadlock
     [exec] :  db_load
     [exec] :  db_checkpoint
     [exec] ./libtool --mode=link cc -O3  -o db_printlog  \
     [exec] 	    db_printlog.o btree_autop.o crdel_autop.o db_autop.o dbreg_autop.o fileops_autop.o hash_autop.o heap_autop.o qam_autop.o repmgr_autop.o txn_autop.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_recover  \
     [exec] 	    db_recover.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_replicate  \
     [exec] 	    db_replicate.o util_log.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_stat  \
     [exec] 	    db_stat.o util_cache.o util_sig.o libdb-5.3.a -lpthread
     [exec] :  db_log_verify
     [exec] ./libtool --mode=link cc -O3  -o db_upgrade  \
     [exec] 	    db_upgrade.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_verify  \
     [exec] 	    db_verify.o util_cache.o util_sig.o libdb-5.3.a -lpthread
     [exec] ./libtool --mode=link cc -O3  -o db_tuner  \
     [exec] 	    db_tuner.o util_sig.o libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_recover db_recover.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_upgrade db_upgrade.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_replicate db_replicate.o util_log.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_verify db_verify.o util_cache.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_stat db_stat.o util_cache.o util_sig.o  libdb-5.3.a -lpthread
     [exec] libtool: link: cc -O3 -o db_printlog db_printlog.o btree_autop.o crdel_autop.o db_autop.o dbreg_autop.o fileops_autop.o hash_autop.o heap_autop.o qam_autop.o repmgr_autop.o txn_autop.o util_sig.o  libdb-5.3.a -lpthread
     [exec] 2 warnings generated.
     [exec] :  db_replicate
     [exec] :  db_verify
     [exec] :  db_upgrade
     [exec] :  db_stat
     [exec] :  db_recover
     [exec] :  db_printlog
     [exec] libtool: link: cc -O3 -o db_tuner db_tuner.o util_sig.o  libdb-5.3.a -lpthread
     [exec] :  db_tuner

ee-build:
     [exec] Traceback (most recent call last):
     [exec]   File "build.py", line 5, in <module>
     [exec]     from buildtools import *
     [exec]   File "/Users/xin/git/h-store/buildtools.py", line 460, in <module>
     [exec]     gcc_major, gcc_minor, gcc_point = getGCCVersion()
     [exec]   File "/Users/xin/git/h-store/buildtools.py", line 457, in getGCCVersion
     [exec]     return int(vinfo[0]), int(vinfo[1]), int(vinfo[2])
     [exec] ValueError: invalid literal for int() with base 10: 'posix'

BUILD FAILED
/Users/xin/git/h-store/build.xml:883: exec returned: 1

Total time: 41 seconds

**Comment by apavlo** [comment]
Sucky :-(

We're probably not going to be able to fix this. I also know that it doesn't compile on gcc 5.
