### ISSUE TITLE
Building H-Store fails for Mac 10.9.5

### ISSUE THREAD

**Issue by pranjalijoshi4** [apavlo/h-store#205]
Hi

I am using Mac 10.9.5 OS and appropriate versions (gcc/g++ - 4.8.5, java -1.7, python - 2.7.5, ant - 1.9.6)
When I try to build h-store, I get an error,

    [javac] /h-store/src/frontend/edu/brown/gui/MarkovViewer.java:171: error: incompatible types: Object cannot be converted to V
    [javac]             vertex = vv.getPickSupport().getVertex(layout,p.getX(), p.getY());
    [javac]                                                                          ^
    [javac]   where V is a type-variable:
    [javac]     V extends Object declared in class PopupMousePlugin
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED

In spite of using appropriate versions, why could this be happening? Is there any issue because of Mac OS?

**Comment by apavlo** [comment]
I don't think H-Store has built correctly on the latest OSX releases because of clang. But this is a Java error which makes me think that it is not picking up 1.7 in your environment properly.

I suggest you use Ubuntu in a VM.
