### ISSUE TITLE
Failed to poll 'site-01-localhost'

### ISSUE THREAD

**Issue by aayush90** [apavlo/h-store#206]
Hi,
I am trying to run tpcc benchmark but it is getting failed.(similar to issue [https://github.com/apavlo/h-store/issues/204](url) )
I have tried to set up passwordless login using procedure given in the documentation
[http://hstore.cs.brown.edu/documentation/deployment/environment/](url)

But still i am getting the same error.

These are the logs i am getting
Starting HStoreSite H00 on localhost

     [java] 10:31:40,410 INFO  - Starting HStoreSite H01 on localhost
     [java] 10:31:40,415 INFO  - Waiting for 2 HStoreSites with 2 partitions to finish initialization
     [java] 10:31:55,411 ERROR - Failed to poll 'site-01-localhost' [exitValue=0]
     [java] 10:31:55,412 FATAL - Process 'site-01-localhost' failed. Halting benchmark!
     [java] 10:31:56,913 FATAL - Failed to complete benchmark
     [java] java.lang.RuntimeException: Failed to start all HStoreSites. Halting benchmark
     [java] 	at edu.brown.api.BenchmarkController.startSites(BenchmarkController.java:634)
     [java] 	at edu.brown.api.BenchmarkController.setupBenchmark(BenchmarkController.java:505)
     [java] 	at edu.brown.api.BenchmarkController.main(BenchmarkController.java:2238)

**Comment by aayush90** [comment]
These are the log files

[site-00-localhost.txt](https://github.com/apavlo/h-store/files/170286/site-00-localhost.txt)
[site-01-localhost.txt](https://github.com/apavlo/h-store/files/170287/site-01-localhost.txt)

**Comment by apavlo** [comment]
Did you read the log file? The error is pretty obvious.

**Comment by aayush90** [comment]
Yes. But which ports are used for binding? I tried to free some but it didn't work out.

**Comment by apavlo** [comment]
The default port is 21212:

https://github.com/apavlo/h-store/blob/master/src/frontend/edu/brown/hstore/HStoreConstants.java#L35

The messenger port is defined as HStoreConstants.DEFAULT_PORT + HStoreConstants.MESSENGER_PORT_OFFSET.

You can see the host port #s in the catalog viewer. I guess I can add it to the catalog-info output if you really need it.

**Comment by aayush90** [comment]
I looked for processes running on port 21212 and even after the benchmark
is executed(failing here), a connection to 21212 is still not closed. So I
think after 1 site H00 is connected, another H01 is not able to connect.
Also I am using Java8 as I am using voltdb-6.1 which needs Java8. Can this
in anyway cause problem?

On Sun, Mar 13, 2016 at 10:25 AM, Andy Pavlo <notifications@github.com>
wrote:

> The default port is 21212:
>
>
> https://github.com/apavlo/h-store/blob/master/src/frontend/edu/brown/hstore/HStoreConstants.java#L35
>
> The messenger port is defined as HStoreConstants.DEFAULT_PORT +
> HStoreConstants.MESSENGER_PORT_OFFSET.
>
> You can see the host port #s in the catalog viewer. I guess I can add it
> to the catalog-info output if you really need it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apavlo/h-store/issues/206#issuecomment-195876970>.
>



-- 
Aayush Singhal
Computer Science and Engineering Department
IIT Kharagpur

**Comment by apavlo** [comment]
I have not tried H-Store on Java8. You will probably want to change the default JDK to Java7.

Also check whether the killstraglers.py script is working. That's designed to clean-up processes before + after each benchmark run.

On Saturday, March 12, 2016 11:54 PM Aayush wrote:
> I looked for processes running on port 21212 and even after the benchmark
> is executed(failing here), a connection to 21212 is still not closed. So I
> think after 1 site H00 is connected, another H01 is not able to connect.
> Also I am using Java8 as I am using voltdb-6.1 which needs Java8. Can this
> in anyway cause problem?
> 
> On Sun, Mar 13, 2016 at 10:25 AM, Andy Pavlo <notifications@github.com>
> wrote:
> 
> > The default port is 21212:
> >
> >
> > https://github.com/apavlo/h-store/blob/master/src/frontend/edu/brown/hstore/HStoreConstants.java#L35
> >
> > The messenger port is defined as HStoreConstants.DEFAULT_PORT +
> > HStoreConstants.MESSENGER_PORT_OFFSET.
> >
> > You can see the host port #s in the catalog viewer. I guess I can add it
> > to the catalog-info output if you really need it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/apavlo/h-store/issues/206#issuecomment-195876970>.
> >
> 
> 
> 
> 

-- 
Andy Pavlo
pavlo@cs.cmu.edu

**Comment by aayush90** [comment]
I tried with Java 7 too but i am getting the same error.
the catalog viewer shows that tpcc project needs 1 host,2 sites,2
partitions with site0 port=21212,site1  port=21213
I checked after starting voltdb instance and it listens only on port 21212
and not on 21213.
Does that mean we need to start 1 voltdb host with 2 sites and this
instance must listen on ports 21212 and 21213.?
If yes then can you help us with how to start voltdb with such
configuration.

Thank You

On Sun, Mar 13, 2016 at 8:51 PM, Andy Pavlo <notifications@github.com>
wrote:

> I have not tried H-Store on Java8. You will probably want to change the
> default JDK to Java7.
>
> Also check whether the killstraglers.py script is working. That's designed
> to clean-up processes before + after each benchmark run.
>
> On Saturday, March 12, 2016 11:54 PM Aayush wrote:
> > I looked for processes running on port 21212 and even after the benchmark
> > is executed(failing here), a connection to 21212 is still not closed. So
> I
> > think after 1 site H00 is connected, another H01 is not able to connect.
> > Also I am using Java8 as I am using voltdb-6.1 which needs Java8. Can
> this
> > in anyway cause problem?
> >
> > On Sun, Mar 13, 2016 at 10:25 AM, Andy Pavlo <notifications@github.com>
> > wrote:
> >
> > > The default port is 21212:
> > >
> > >
> > >
> https://github.com/apavlo/h-store/blob/master/src/frontend/edu/brown/hstore/HStoreConstants.java#L35
> > >
> > > The messenger port is defined as HStoreConstants.DEFAULT_PORT +
> > > HStoreConstants.MESSENGER_PORT_OFFSET.
> > >
> > > You can see the host port #s in the catalog viewer. I guess I can add
> it
> > > to the catalog-info output if you really need it.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/apavlo/h-store/issues/206#issuecomment-195876970>.
> > >
> >
> >
> >
> >
>
> --
> Andy Pavlo
> pavlo@cs.cmu.edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apavlo/h-store/issues/206#issuecomment-195975832>.
>



-- 
Aayush Singhal
Computer Science and Engineering Department
IIT Kharagpur
