### ISSUE TITLE
Two errors occur when I run 'ant build', seems 

### ISSUE THREAD

**Issue by Meditator-hkx** [apavlo/h-store#213]
Error info occurs as below:

1. `[javac] /home/kaixin/h-store/src/frontend/edu/brown/statistics/ProcedureStatistics.java:168: error: reference to put is ambiguous
     [javac]                 this.proc_param_histograms.get(i).put(xact.getParam(i));`

2. `[javac] /home/kaixin/h-store/src/frontend/edu/brown/gui/MarkovViewer.java:171: error: incompatible types: Object cannot be converted to V
    [javac]             vertex = vv.getPickSupport().getVertex(layout,p.getX(), p.getY());`

My environment is Ubuntu 16.04 with gcc-4.8, ant-1.9, openjdk-1.8, python-2.7.

As a newer in Database area, I am just confused about this and wonder if I should modify the code according to the error tips.

**Comment by apavlo** [comment]
This looks like a java 1.8 error. I have not tested it with newer versions of the JVM. Try it with 1.7

**Comment by Meditator-hkx** [comment]
Oh, I see, thank you.

**Comment by Meditator-hkx** [comment]
Hey, sorry to disturb you, but new problems occur as below:

`berkeleydb.compile:
  ee-build:
     [exec] Error Determining Dependencies for: src/ee//voltdbjni.cpp
     [exec] src/ee//voltdbjni.cpp:57:20: error: signal.h: No such file or directory
     [exec] src/ee//voltdbjni.cpp:58:19: error: dlfcn.h: No such file or directory
     [exec] src/ee//voltdbjni.cpp:82:23: error: mach/task.h: No such file or directory
     [exec] src/ee//voltdbjni.cpp:83:23: error: mach/mach.h: No such file or directory
     [exec] In file included from src/ee//voltdbjni.cpp:100:
     [exec] src/ee//common/debuglog.h:60:22: error: sys/time.h: No such file or directory
     [exec] In file included from src/ee//voltdbjni.cpp:101:
     [exec] src/ee//common/serializeio.h:53:23: error: arpa/inet.h: No such file or directory
     [exec] In file included from src/ee//common/TheHashinator.h:21,
     [exec]                  from src/ee//voltdbjni.cpp:102:
     [exec] src/ee/common/FatalException.hpp:24:22: error: execinfo.h: No such file or directory
     [exec] src/ee/common/FatalException.hpp:30:23: error: sys/types.h: No such file or directory
     [exec] src/ee/common/FatalException.hpp:31:22: error: sys/stat.h: No such file or directory
     [exec] src/ee/common/FatalException.hpp:32:19: error: fcntl.h: No such file or directory
     [exec] In file included from src/ee/common/NValue.hpp:37,
     [exec]                  from src/ee//common/TheHashinator.h:22,
     [exec]                  from src/ee//voltdbjni.cpp:102:
     [exec] src/ee/common/Pool.hpp:23:22: error: sys/mman.h: No such file or directory
     [exec] src/ee/common/Pool.hpp:24:19: error: errno.h: No such file or directory
     [exec]

BUILD FAILED`

The environment this time: Ubuntu 14.04, python 2.7, gcc 4.3, openjdk-1.7.
I am not sure why these happen, because I think all the configuration of tools should be right...

**Comment by Meditator-hkx** [comment]
I have made it successful in Ubuntu 14.04 this time with gcc-4.8, openjdk-1.7. 
Thanks for your advice.
