### ISSUE TITLE
Anti-caching seems not working well in my configuration setup

### ISSUE THREAD

**Issue by Meditator-hkx** [apavlo/h-store#215]
Hello, recently I am trying to understand the design of "anti-caching".

When I try to enable the anti-caching ability for h-store, it seems doesn't work.

Concretely,  I wrote a bash script as follows:

```
#!/bin/bash

export dataDir=./data
cd ./data/

touch throughput.csv
touch memory.csv
touch evictions.csv

cd ..

ant compile hstore-benchmark -Dproject=tpcc \
    -Dclient.interval=500 \
    -Dsite.anti_cache_enable=true \
    -Dsite.anticache_profiling=true \
    -Dsite.anticache_block_size=262144 \
    -Dsite.anticache_dbsize=1G \
    -Dclient.anticache_enable=true \
    -Dclient.anticache_evict_interval=3000 \
    -Dclient.anticache_evict_size=2097152 \
    -Dclient.output_memory=$dataDir/memory.csv \
    -Dclient.output_csv=$dataDir/throughput.csv \
    -Dclient.output_anticache_history=$dataDir/evictions.csv
```

However, when I checked the throughput.csv file, the column of "evictions" was all left 0s. And I run again with setting "anticache_enable=false", the througput for tpcc benchmark was almost the same.

I tried to modify the scalefactor in "default.properties" file but anti-caching still didn't work.
My machine use Linux Ubuntu 14.04 with main memory of 8GB.

So could you kindly tell if there is something wrong with my setup, either for parameters or benchmarks? Thank you!

**Comment by apavlo** [comment]
Did you mark which tables you want the system to write out to disk using the `evictable` flag with `hstore-prepare`? See the first example under **Usage**: 

http://hstore.cs.brown.edu/documentation/deployment/anti-caching/

**Comment by Meditator-hkx** [comment]
Oh, thanks a lot, it's my mistake. By setting the "-Devictable" parameter, it can currently work well. But my another confusion is, how can I properly set the benchmark data size and scalefactor (for example, tpcc) to promise that eviction will certainly happen? I didn't see any configuration about initial data size setting in benchmark propertie file.

**Comment by apavlo** [comment]
You can't set an exact amount because it is dependent on the benchmark. For TPC-C you can tweak both the scale factor and the number of warehouses.

**Comment by Meditator-hkx** [comment]
Thanks, I'll try this way.
