### ISSUE TITLE
Controlling the Data size for the tpcc

### ISSUE THREAD

**Issue by mmmohsen** [apavlo/h-store#216]
Hello world,
[assume the tpc-c benchmark]
so to control the data size, I should use the scaling factor parameter....  so what does it mean to have a scale factor of 5 for example in terms of bytes/Giga bytes? how does this relate to the number of warehouses.

lastly .... If I use configurations like the following [the default configurations]
2 sites
2 partitions per sites......

does this mean that the data will be replicated 4 times?  

Thank you a lot in advance.

**Comment by apavlo** [comment]
> so to control the data size, I should use the scaling factor parameter.... 

You can control either the number of warehouses in TPC-C:

https://github.com/apavlo/h-store/blob/master/properties/benchmarks/tpcc.properties#L15

Or you can set the scale factor. The scale factor will change the # of customers and initial orders:

https://github.com/apavlo/h-store/blob/master/src/benchmarks/org/voltdb/benchmark/tpcc/ScaleParameters.java#L91

> lastly .... If I use configurations like the following [the default configurations]
> 2 sites
> 2 partitions per sites......
> does this mean that the data will be replicated 4 times?

No, this means that the database will be split up into four distinct partitions. You can use the `catalog-info` command line tool to see what your cluster looks like:

http://hstore.cs.brown.edu/documentation/configuration/cluster-file/
