### ISSUE TITLE
Debugging the ee with new indexing file?

### ISSUE THREAD

**Issue by dvirginz** [apavlo/h-store#217]
I'm trying to create a new index mechanism for the ee of hstore, and encounters crashes at
ant hstore-benchmark -Dproject=tpcc -Dnoexecute=true -Dnoshutdown=true

which makes sense, as my indexing effects the buildup of the DB.
Anyone here managed to use different indexes from the ones used, and was able to debug the process?

**Comment by apavlo** [comment]
Nobody works on this project anymore. See @huanchenz's patches from a few years ago for his hybrid index project:

https://github.com/huanchenz/h-store/commit/ad309ac807ba5b6d1976a44e16cab643d84fe567
